//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyMasterMetaData
    {
        public int CompanyMasterMetadataID { get; set; }
        public string WorkBook { get; set; }
        public string FileName { get; set; }
        public string NAICSCode { get; set; }
        public string SeriesName { get; set; }
        public string NSA { get; set; }
        public string Continent { get; set; }
        public string Country { get; set; }
        public string Region { get; set; }
        public string State { get; set; }
        public string MSA { get; set; }
        public string Category { get; set; }
        public string Subcategory { get; set; }
        public string Units { get; set; }
        public string BASE { get; set; }
        public string Source { get; set; }
        public string Link { get; set; }
        public string Definition { get; set; }
    }
}
