//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerDataSet
    {
        public int CustomerDataSetID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public string DataSetName { get; set; }
        public string DataSetDescription { get; set; }
        public string CustomerID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string CompanyName { get; set; }
        public string DataType { get; set; }
        public string Base { get; set; }
        public string Units { get; set; }
        public string CompanyWebsite { get; set; }
        public Nullable<bool> IsITREmployee { get; set; }
        public string UserName { get; set; }
    }
}
