//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int CustomerProdId { get; set; }
        public string CustomerName { get; set; }
        public string CompanyName { get; set; }
        public string DataType { get; set; }
        public string Base { get; set; }
        public string Units { get; set; }
        public string CompanyWebsite { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string UploadedBy { get; set; }
        public Nullable<System.DateTime> UploadedDate { get; set; }
    }
}
