//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int ExceptionID { get; set; }
        public string CustomerID { get; set; }
        public string ExceptionMessage { get; set; }
        public string PageName { get; set; }
        public string CreatedBY { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
