//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForecastSummary
    {
        public int FSID { get; set; }
        public string DOSCode { get; set; }
        public Nullable<System.DateTime> ForecastDate { get; set; }
        public Nullable<System.DateTime> DataThrough { get; set; }
        public string CheckedBy { get; set; }
        public Nullable<System.DateTime> LastChecked { get; set; }
        public Nullable<System.DateTime> DateOfData { get; set; }
        public string ForecastStatus { get; set; }
        public string UpcomingHighLow { get; set; }
        public string NextHighLow { get; set; }
        public string ThirdHighLow { get; set; }
        public string ForecastCheckNote { get; set; }
        public string TemplateVersion { get; set; }
        public string FileSubfolderName { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
