//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StagingForecastTest
    {
        public int Sysid { get; set; }
        public string MonthYear { get; set; }
        public string ForeCastType { get; set; }
        public string C12MMTLFR { get; set; }
        public string C12MMTAverage { get; set; }
        public string C12MMTUFR { get; set; }
        public string C3MMTLFR { get; set; }
        public string C3MMTAverage { get; set; }
        public string C3MMTUFR { get; set; }
        public string C1212MMTLFR { get; set; }
        public string C1212MMTAverage { get; set; }
        public string C1212MMTUFR { get; set; }
        public string C312MMTLFR { get; set; }
        public string C312MMTAverage { get; set; }
        public string C312MMTUFR { get; set; }
        public string Q_To_Q { get; set; }
        public string Spread { get; set; }
        public string C1212MMTVarianceL1 { get; set; }
        public string C1212MMTVarianceL2 { get; set; }
        public string C1212MMTVarianceL3 { get; set; }
        public string C1212MMTActualL1 { get; set; }
        public string C1212MMTActualL2 { get; set; }
        public string C1212MMTActualL3 { get; set; }
        public Nullable<int> ShortCodesId { get; set; }
    }
}
