//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StateProvince
    {
        public int StateProvinceID { get; set; }
        public string Name { get; set; }
        public string ShortCode { get; set; }
        public Nullable<int> CountryID { get; set; }
        public string IsState { get; set; }
        public string IsProvince { get; set; }
    }
}
