//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubProduct
    {
        public int SubProductID { get; set; }
        public string SubProductName { get; set; }
        public string SubProductDescription { get; set; }
        public Nullable<int> ProductID { get; set; }
    }
}
