//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempTable
    {
        public int TempTableID { get; set; }
        public string ShortCode { get; set; }
        public Nullable<System.DateTime> MonthYear { get; set; }
        public Nullable<decimal> C3BY12 { get; set; }
        public Nullable<decimal> C12BY12 { get; set; }
        public string HighLow { get; set; }
        public Nullable<int> VoilenceLength { get; set; }
        public string BusniessPhase { get; set; }
    }
}
