//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TEMP_CompanyReporting_Logic
    {
        public int ID { get; set; }
        public Nullable<int> SourceID { get; set; }
        public Nullable<System.DateTime> DateMonth { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> MonthlyValue { get; set; }
        public Nullable<decimal> OneByTwelveMMA { get; set; }
        public Nullable<decimal> OneByTwelveMMT { get; set; }
        public Nullable<decimal> ThreeMMA { get; set; }
        public Nullable<decimal> ThreeByTwelveMMA { get; set; }
        public Nullable<decimal> ThreeByTwelveMMT { get; set; }
        public Nullable<decimal> TwelveMMA { get; set; }
        public Nullable<decimal> TwelveByTwelveMMA { get; set; }
        public Nullable<decimal> TwelveByTwelveMMT { get; set; }
        public Nullable<decimal> ThreeMMT { get; set; }
        public Nullable<decimal> TwelveMMT { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ProductCategoryID { get; set; }
        public bool IsProcessed { get; set; }
        public Nullable<decimal> AdjValue { get; set; }
        public string ShortCode { get; set; }
        public Nullable<bool> FLAG { get; set; }
    }
}
