//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UI_ForeCastMetaData
    {
        public int ForeCastMetaDataID { get; set; }
        public string ShortCode { get; set; }
        public Nullable<System.DateTime> ForeCastDate { get; set; }
        public string ForeCaster { get; set; }
        public string ProofedBy { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> DataThruDate { get; set; }
    }
}
