//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDataSet
    {
        public int DatasetID { get; set; }
        public string DatasetShortcode { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> DivisionId { get; set; }
        public string DivisionName { get; set; }
    }
}
