//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTableau
    {
        public string DataType { get; set; }
        public string Company_Name { get; set; }
        public Nullable<int> DB_AccountID { get; set; }
        public string AccountName { get; set; }
        public Nullable<int> DB_DivisionID { get; set; }
        public string DivisionName { get; set; }
        public string Indicator { get; set; }
        public string Indicator_Name { get; set; }
        public Nullable<double> lagValue { get; set; }
        public Nullable<double> CorrValue { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public Nullable<decimal> C1BY12_Indicator { get; set; }
        public Nullable<decimal> C3MMT_Indicator { get; set; }
        public Nullable<decimal> C3BY12_Indicator { get; set; }
        public Nullable<decimal> C3MMA_Indicator { get; set; }
        public Nullable<decimal> C12MMT_Indicator { get; set; }
        public Nullable<decimal> C12BY12_Indicator { get; set; }
        public Nullable<decimal> C12MMA_Indicator { get; set; }
        public Nullable<decimal> Monthly_Indicator { get; set; }
        public Nullable<decimal> C1BY12_Company { get; set; }
        public Nullable<decimal> C3MMT_Company { get; set; }
        public Nullable<decimal> C3BY12_Company { get; set; }
        public Nullable<decimal> C3MMA_Company { get; set; }
        public Nullable<decimal> C12MMT_Company { get; set; }
        public Nullable<decimal> C12BY12_Company { get; set; }
        public Nullable<decimal> C12MMA_Company { get; set; }
        public Nullable<decimal> Monthly_Company { get; set; }
        public Nullable<int> Forecast { get; set; }
        public string Range { get; set; }
    }
}
