//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ITR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWTBL_INDICATOR
    {
        public Nullable<System.DateTime> MonthYear { get; set; }
        public Nullable<decimal> C1By12 { get; set; }
        public Nullable<decimal> C3MMT { get; set; }
        public Nullable<decimal> C3BY12 { get; set; }
        public Nullable<decimal> C3MMA { get; set; }
        public Nullable<decimal> C12MMT { get; set; }
        public Nullable<decimal> C12BY12 { get; set; }
        public Nullable<decimal> C12MMA { get; set; }
        public Nullable<decimal> Sales { get; set; }
        public string SHORTCODE { get; set; }
        public Nullable<decimal> Monthly { get; set; }
        public int VwTblIndicatorID { get; set; }
        public string Phases { get; set; }
        public Nullable<int> Violencing { get; set; }
        public string HighLow { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
    }
}
